name: Python CI

on:
  workflow_dispatch:


jobs:
  tests:
    runs-on: ubuntu-lastest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run app
      run: |
        cd application
        uvicorn main:app --reload
    - name: Sleep for 90 seconds
      run: sleep 90s
      shell: bash
