name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-lastest

    steps:
      - uses: actions/checkout@v3
      - name: Print folder
        run: |
          ls
